/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zavrsnirad.view;

import java.sql.Date;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import zavrsnirad.controller.ObradaKlijent_kupac;
import zavrsnirad.controller.ObradaKorisnik;
import zavrsnirad.controller.ObradaRacun;
import zavrsnirad.controller.ObradaStavka;
import zavrsnirad.controller.ObradaUsluga_proizvod;
import zavrsnirad.model.Klijent_kupac;
import zavrsnirad.model.Korisnik;
import zavrsnirad.model.Racun;
import zavrsnirad.model.Stavka;
import zavrsnirad.model.Usluga_proizvod;
import zavrsnirad.utility.DelagaException;
import zavrsnirad.view.ViewAutorizacija;

/**
 *
 * @author mirza
 */
public class ViewRacun extends javax.swing.JFrame {

    private ViewGlavni glavni;
    private Racun r;
    private ObradaStavka obradaStavka;
    private ObradaRacun obradaRacun;
    private ObradaKorisnik obradaKorisnik;
    private Korisnik trenutniKorisnik;
    /**
     * Creates new form ViewRacun
     */
    public ViewRacun(ViewGlavni r) {
        initComponents();
        this.glavni = r;
        this.r = glavni.getOdabraniRacun();
        
        ucitajUsluge();
        ucitajKlijenteKupce();

        System.out.println(this.r.getKorisnik().getEmail());
        
        ButtonGroup group = new ButtonGroup();
        group.add(rbtRobaDomaci);
        group.add(rbtRobaInozemni);
        group.add(rbtUslugeDomaci);
        group.add(rbtUslugeInozemni);
        if (this.r.getId() == null) {
            
            
            
            txtBrojRacuna.setText(this.r.getBroj_racuna());
            txtIzdaoKorisnik.setText(this.r.getKorisnik().getPrezime());
            TableColumn tc = tblStavke.getColumnModel().getColumn(0);
            tc.setWidth(0);
            tc.setMinWidth(0);
            tc.setMaxWidth(0);
            
            //txtIzdaoKorisnik.setText(trenutniKorisnik.getPrezime());
            
            
            
            
            

        } else {
            ucitajRacun();

        }

    }

    private void ucitajRacun() {
        txtBrojRacuna.setText(r.getBroj_racuna());
        //dtcVrijemeIzdavanja.setDateTimePermissive(r.getDatum_izdavanja().toLocalDate().atStartOfDay());
        dtcDatumIzdavanja.setDate(r.getDatum_izdavanja());
        timeVrijemeIzdavanja.setTime(r.getVrijemeIzdavanja().toLocalTime());
        dtcDatumIsporuke.setDate(r.getDatum_isporuke());
        txtIzdaoKorisnik.setText(r.getKorisnik().getPrezime());

        txtNacinPlacanja.setText(r.getNacin_placanja());
        dtcDatumDospijeca.setDate(r.getDatum_dospijeca());
        txtfNapomena.setText(r.getNapomena());

        DefaultTableModel dtm = (DefaultTableModel) tblStavke.getModel();
        List<Stavka> stavke = r.getStavke();
        String[] colNames = {"objekt", "Naziv", "Jed. mj.", "Cijena", "Kolićina", "Rabat", "Iznos"};
        for (int i = 0; i < colNames.length; i++) {
            
            TableColumn tc = tblStavke.getColumnModel().getColumn(i);
            tc.setHeaderValue(colNames[i]);
            if (i == 0) {
                tc.setWidth(0);
                tc.setMinWidth(0);
                tc.setMaxWidth(0);
            }
        }
        for (Stavka s : stavke) {

            Object[] red = {
                s,
                s.getProizvod().getNaziv(),
                s.getProizvod().getJedinica_mjere(),
                s.getProizvod().getCijena().toString(),
                s.getKolicina(),
                s.getRabat(),
                s.getIznosStavke()

            };
            dtm.addRow(red);
        }

        txtUkupno.setText(r.getIznos_racuna().toString() + " HRK");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngGroup = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtfNapomena = new javax.swing.JTextArea();
        txtBrojRacuna = new javax.swing.JTextField();
        txtIzdaoKorisnik = new javax.swing.JTextField();
        txtNacinPlacanja = new javax.swing.JTextField();
        rbtUslugeDomaci = new javax.swing.JRadioButton();
        rbtUslugeInozemni = new javax.swing.JRadioButton();
        rbtRobaDomaci = new javax.swing.JRadioButton();
        rbtRobaInozemni = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        btnSpremi = new javax.swing.JButton();
        btnSpremiIIspisi = new javax.swing.JButton();
        btnIIspisi = new javax.swing.JButton();
        btnObrisi1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        dtcDatumDospijeca = new com.toedter.calendar.JDateChooser();
        dtcDatumIsporuke = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        cmbStavkaNaziv = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtStavkaJedinicaMjere = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtStavkaCijena = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        spnStavkaKolicina = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        txtStavkaRabat = new javax.swing.JTextField();
        txtStavkaIznos = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtStavkaOpis = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        btnStavkaDodaj = new javax.swing.JButton();
        btnStavkaObrisi = new javax.swing.JButton();
        txtUkupno = new javax.swing.JTextField();
        cmbKlijentKupac = new javax.swing.JComboBox<>();
        timeVrijemeIzdavanja = new com.github.lgooddatepicker.components.TimePicker();
        dtcDatumIzdavanja = new com.toedter.calendar.JDateChooser();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(1091, 621));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Račun ..."));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 840));

        jLabel1.setText("Broj računa:");

        jLabel2.setText("Klijent / Kupac:");

        jLabel3.setText("Vrijeme izdavanja:");

        jLabel4.setText("Datum dospijeća:");

        jLabel5.setText("Datum isporuke:");

        jLabel6.setText("Izdao korisnik:");

        jLabel7.setText("Napomena:");

        jLabel8.setText("Način plačanja:");

        txtfNapomena.setColumns(20);
        txtfNapomena.setRows(5);
        jScrollPane1.setViewportView(txtfNapomena);

        txtIzdaoKorisnik.setEditable(false);

        rbtUslugeDomaci.setSelected(true);
        rbtUslugeDomaci.setText("Usluge:Domaći");
        rbtUslugeDomaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtUslugeDomaciActionPerformed(evt);
            }
        });

        rbtUslugeInozemni.setText("Usluge:Inozemni");
        rbtUslugeInozemni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtUslugeInozemniActionPerformed(evt);
            }
        });

        rbtRobaDomaci.setText("Roba:Domaći");
        rbtRobaDomaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtRobaDomaciActionPerformed(evt);
            }
        });

        rbtRobaInozemni.setText("Roba:Inozemni");
        rbtRobaInozemni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtRobaInozemniActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke ..."));

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stavka", "Naziv", "jed.mj.", "Cijena", "Količina", "Rabat", "Iznos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStavke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStavkeMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblStavke);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnSpremi.setText("Spremi");
        btnSpremi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpremiActionPerformed(evt);
            }
        });

        btnSpremiIIspisi.setText("Spremi i ispiši");
        btnSpremiIIspisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpremiIIspisiActionPerformed(evt);
            }
        });

        btnIIspisi.setText("Ispiši");
        btnIIspisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIIspisiActionPerformed(evt);
            }
        });

        btnObrisi1.setText("Obriši");
        btnObrisi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisi1ActionPerformed(evt);
            }
        });

        jLabel9.setText("UKUPNO:");
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Odabrana stavka ..."));

        cmbStavkaNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStavkaNazivActionPerformed(evt);
            }
        });

        jLabel10.setText("Naziv stavke");

        jLabel11.setText("Jedinica mjere:");

        jLabel12.setText("Cijena");

        jLabel14.setText("Količina");

        jLabel15.setText("Rabat (%)");

        txtStavkaRabat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStavkaRabatActionPerformed(evt);
            }
        });

        txtStavkaIznos.setEnabled(false);

        jLabel13.setText("IZNOS");
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtStavkaOpis.setColumns(20);
        txtStavkaOpis.setRows(5);
        jScrollPane2.setViewportView(txtStavkaOpis);

        jLabel16.setText("Opis:");

        btnStavkaDodaj.setText("Dodaj stavku");
        btnStavkaDodaj.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnStavkaDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStavkaDodajActionPerformed(evt);
            }
        });

        btnStavkaObrisi.setText("Obriši stavku");
        btnStavkaObrisi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnStavkaObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStavkaObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbStavkaNaziv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStavkaRabat, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(txtStavkaIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStavkaCijena, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStavkaJedinicaMjere, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnStavkaKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStavkaObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(btnStavkaDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbStavkaNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtStavkaJedinicaMjere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtStavkaCijena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(spnStavkaKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtStavkaRabat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtStavkaIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnStavkaDodaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStavkaObrisi)
                .addContainerGap())
        );

        txtUkupno.setEditable(false);
        txtUkupno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtUkupno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUkupno.setDisabledTextColor(new java.awt.Color(0, 0, 204));
        txtUkupno.setEnabled(false);
        txtUkupno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUkupnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(rbtUslugeInozemni)
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtRobaInozemni)
                                    .addComponent(rbtRobaDomaci)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbtUslugeDomaci)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIzdaoKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNacinPlacanja, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(dtcDatumIsporuke, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                        .addComponent(dtcDatumDospijeca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtBrojRacuna, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbKlijentKupac, javax.swing.GroupLayout.Alignment.LEADING, 0, 221, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dtcDatumIzdavanja, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(timeVrijemeIzdavanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSpremi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnIIspisi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSpremiIIspisi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisi1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtBrojRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(cmbKlijentKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(timeVrijemeIzdavanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dtcDatumIzdavanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(dtcDatumDospijeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(dtcDatumIsporuke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtIzdaoKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtNacinPlacanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtUslugeDomaci)
                                    .addComponent(rbtRobaDomaci))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtUslugeInozemni)
                                    .addComponent(rbtRobaInozemni)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnSpremi)
                                            .addComponent(btnIIspisi)
                                            .addComponent(btnSpremiIIspisi))
                                        .addGap(41, 41, 41))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnObrisi1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStavkaObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStavkaObrisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStavkaObrisiActionPerformed

    private void btnStavkaDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStavkaDodajActionPerformed
        Stavka s = new Stavka();
        DefaultTableModel dtm = (DefaultTableModel) tblStavke.getModel();
        s.setProizvod((Usluga_proizvod) cmbStavkaNaziv.getSelectedItem());
        s.setKolicina(BigDecimal.parseBigDecimal(String.valueOf(spnStavkaKolicina.getValue())));
        if (txtStavkaRabat.getText().trim().length() > 0) {
            s.setRabat(BigDecimal.parseBigDecimal(txtStavkaRabat.getText()));
        } else {
            s.setRabat(0);
        }

        s.setIznosStavke(s.getIznosStavke());
        s.setRacun(r);
        Object[] red = {
            s,
            s.getProizvod().getNaziv(),
            s.getProizvod().getJedinica_mjere(),
            s.getProizvod().getCijena().toString(),
            s.getKolicina(),
            s.getRabat(),
            s.getIznosStavke()

        };
        dtm.addRow(red);
        tblStavke.repaint();


    }//GEN-LAST:event_btnStavkaDodajActionPerformed

    private void cmbStavkaNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStavkaNazivActionPerformed
        Usluga_proizvod p = (Usluga_proizvod) cmbStavkaNaziv.getSelectedItem();
        txtStavkaCijena.setText(p.getCijena().toString());
        txtStavkaJedinicaMjere.setText(p.getJedinica_mjere());
        txtStavkaOpis.setText(p.getOpis());
    }//GEN-LAST:event_cmbStavkaNazivActionPerformed

    private void btnObrisi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnObrisi1ActionPerformed

    private void btnIIspisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIIspisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIIspisiActionPerformed

    private void btnSpremiIIspisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpremiIIspisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSpremiIIspisiActionPerformed

    private void btnSpremiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpremiActionPerformed
        //provjera da li racun postoji
        
        //upozori ako je isti broj
        //ako nije spremi ga sa novim brojem
        
        this.r.setBroj_racuna(txtBrojRacuna.getText());
        this.r.setDatum_dospijeca(new java.sql.Date(dtcDatumDospijeca.getDate().getTime()));
        this.r.setDatum_isporuke( new java.sql.Date(dtcDatumIsporuke.getDate().getTime()));
        this.r.setDatum_izdavanja(new java.sql.Date(dtcDatumIzdavanja.getDate().getTime()));
        this.r.setVrijemeIzdavanja(Time.valueOf(timeVrijemeIzdavanja.getTime()));
        this.r.setKlijent_kupac((Klijent_kupac) cmbKlijentKupac.getSelectedItem());
        this.r.setNacin_placanja(txtNacinPlacanja.getText());
        this.r.setNapomena(txtfNapomena.getText());
        this.r.setVrstaRacuna(1);
        List<Stavka> stavke=new ArrayList<>();
        int brojRedova=tblStavke.getModel().getRowCount();
        for(int i=0; i<brojRedova;i++){
            stavke.add((Stavka) tblStavke.getModel().getValueAt(i, 0)) ;
        }
        
        this.r.setVrijemeKreiranja(Date.valueOf(LocalDate.now()));
        this.r.setVrijemePromjene(Date.valueOf(LocalDate.now()));
        this.r.setStavke(stavke);
        
        try {
            obradaRacun.spremi(r);
        } catch (DelagaException ex) {
            ex.printStackTrace();
        }
        //na kraju
        glavni.ucitaj();
        dispose();
    }//GEN-LAST:event_btnSpremiActionPerformed

    private void tblStavkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStavkeMouseClicked

        Stavka s = (Stavka) tblStavke.getValueAt(tblStavke.getSelectedRow(), 0);
        //System.out.println(tblStavke.getValueAt(tblStavke.getSelectedRow(), 0));
        //comStavkaNaziv.setSelectedItem(s.getProizvod().getNaziv());
        //comStavkaNaziv.setSelectedIndex(s.getId());

        //ovo isto tako na kupca
        DefaultComboBoxModel<Usluga_proizvod> mp
                = (DefaultComboBoxModel<Usluga_proizvod>) cmbStavkaNaziv.getModel();

        for (int i = 0; i < mp.getSize(); i++) {
            if (mp.getElementAt(i).getId().equals(
                    s.getProizvod().getId())) {
                cmbStavkaNaziv.setSelectedIndex(i);
                break;
            }

        }

        txtStavkaCijena.setText(s.getProizvod().getCijena().toString());
        txtStavkaJedinicaMjere.setText(s.getProizvod().getJedinica_mjere());
        spnStavkaKolicina.setValue(s.getKolicina());
        txtStavkaOpis.setText(s.getProizvod().getOpis());
        txtStavkaIznos.setText("" + s.getIznosStavke());
    }//GEN-LAST:event_tblStavkeMouseClicked

    private void rbtRobaInozemniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtRobaInozemniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtRobaInozemniActionPerformed

    private void rbtRobaDomaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtRobaDomaciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtRobaDomaciActionPerformed

    private void rbtUslugeInozemniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtUslugeInozemniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtUslugeInozemniActionPerformed

    private void rbtUslugeDomaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtUslugeDomaciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtUslugeDomaciActionPerformed

    private void txtUkupnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUkupnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUkupnoActionPerformed

    private void txtStavkaRabatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStavkaRabatActionPerformed

    }//GEN-LAST:event_txtStavkaRabatActionPerformed
    private void ucitajKlijenteKupce() {

        DefaultComboBoxModel<Klijent_kupac> mod = new DefaultComboBoxModel<>();
        Klijent_kupac kk = new Klijent_kupac();
        kk.setId(0);
        kk.setNaziv("Odaberite kupca");
        mod.addElement(kk);
        new ObradaKlijent_kupac().getEntiteti().forEach((klijentKupac) -> {
            mod.addElement(klijentKupac);
        });
        cmbKlijentKupac.setModel(mod);
        if (r.getId() != null) {

            for (int i = 0; i < mod.getSize(); i++) {
                if (mod.getElementAt(i).getId().equals(
                        this.r.getKlijent_kupac().getId())) {
                    cmbKlijentKupac.setSelectedIndex(i);
                    break;
                }
            }

        }
    }

    private void ucitajProizvodeUsluge() {

        DefaultComboBoxModel<Usluga_proizvod> m = new DefaultComboBoxModel<>();
        Usluga_proizvod up = new Usluga_proizvod();
        up.setId(0);
        up.setNaziv("Odaberite proizvod");
        m.addElement(up);

        new ObradaUsluga_proizvod().getEntiteti().forEach((uslugaProizvod) -> {
            m.addElement(uslugaProizvod);
        });
        cmbStavkaNaziv.setModel(m);

    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIIspisi;
    private javax.swing.JButton btnObrisi1;
    private javax.swing.JButton btnSpremi;
    private javax.swing.JButton btnSpremiIIspisi;
    private javax.swing.JButton btnStavkaDodaj;
    private javax.swing.JButton btnStavkaObrisi;
    private javax.swing.ButtonGroup btngGroup;
    private javax.swing.JComboBox<Klijent_kupac> cmbKlijentKupac;
    private javax.swing.JComboBox<Usluga_proizvod> cmbStavkaNaziv;
    private com.toedter.calendar.JDateChooser dtcDatumDospijeca;
    private com.toedter.calendar.JDateChooser dtcDatumIsporuke;
    private com.toedter.calendar.JDateChooser dtcDatumIzdavanja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton rbtRobaDomaci;
    private javax.swing.JRadioButton rbtRobaInozemni;
    private javax.swing.JRadioButton rbtUslugeDomaci;
    private javax.swing.JRadioButton rbtUslugeInozemni;
    private javax.swing.JSpinner spnStavkaKolicina;
    private javax.swing.JTable tblStavke;
    private com.github.lgooddatepicker.components.TimePicker timeVrijemeIzdavanja;
    private javax.swing.JTextField txtBrojRacuna;
    private javax.swing.JTextField txtIzdaoKorisnik;
    private javax.swing.JTextField txtNacinPlacanja;
    private javax.swing.JTextField txtStavkaCijena;
    private javax.swing.JTextField txtStavkaIznos;
    private javax.swing.JTextField txtStavkaJedinicaMjere;
    private javax.swing.JTextArea txtStavkaOpis;
    private javax.swing.JTextField txtStavkaRabat;
    private javax.swing.JTextField txtUkupno;
    private javax.swing.JTextArea txtfNapomena;
    // End of variables declaration//GEN-END:variables

    private void ucitajUsluge() {
        DefaultComboBoxModel<Usluga_proizvod> m = new DefaultComboBoxModel<>();
        Usluga_proizvod pr = new Usluga_proizvod();
        pr.setId(0);
        pr.setNaziv("Odaberite");
        m.addElement(pr);

        new ObradaUsluga_proizvod().getEntiteti().forEach((p) -> {
            m.addElement(p);
        });
        cmbStavkaNaziv.setModel(m);

    }

}
